import Link from "next/link";
import { chapters, glossary, reviewQuestions } from "../data/materials";
import { Icon, SiteFooter, SiteHeader } from "../components/SiteChrome";
import ProgressPanel from "../components/ProgressPanel";

export default function Home(){
  return <main><SiteHeader/>
    <section id="atas" className="hero shell"><div className="hero-copy"><div className="eyebrow"><span>COMPTIA TECH+</span><i/> FC0-U71 · VERSION 2.2</div><h1>Fondasi IT yang<br/><em>runtut dan utuh.</em></h1><p>Materi belajar berbahasa Indonesia untuk memahami seluruh domain CompTIA Tech+. Setiap bab tersedia pada halaman tersendiri agar fokus dan mudah dinavigasi.</p><div className="hero-actions"><Link className="button primary" href="/materi/bab-1">Mulai dari Bab 1 <Icon name="arrow" size={18}/></Link><Link className="button soft" href="/materi">Lihat seluruh bab</Link></div><div className="exam-facts"><div><strong>6</strong><span>domain utama</span></div><div><strong>31</strong><span>subbab materi</span></div><div><strong>60</strong><span>menit ujian</span></div><div><strong>650</strong><span>skor kelulusan</span></div></div></div>
      <ProgressPanel chapters={chapters.map(({id,shortTitle})=>({id,shortTitle}))}/>
    </section>
    <section className="blueprint-strip"><div className="shell">{chapters.map(ch=><Link href={`/materi/bab-${ch.id}`} key={ch.id}><span>0{ch.id}</span><b>{ch.weight}%</b></Link>)}</div></section>

    <section id="materi" className="chapter-catalog shell"><div className="catalog-heading"><div><span className="section-label">PETA MATERI</span><h2>Enam bab.<br/>Enam halaman terfokus.</h2></div><p>Pilih bab untuk membuka materi lengkap. Di dalam setiap halaman tersedia daftar subbab, navigasi bab sebelumnya dan berikutnya, serta penanda progres.</p></div><div className="chapter-card-grid">{chapters.map(ch=><Link className="chapter-card" href={`/materi/bab-${ch.id}`} key={ch.id}><div className="card-top"><span>0{ch.id}</span><b>{ch.weight}%</b></div><div className="card-body"><small>{ch.sections.length} SUBBAB</small><h3>{ch.title}</h3><p>{ch.description}</p></div><div className="card-action"><span>Buka bab</span><Icon name="arrow" size={18}/></div></Link>)}</div></section>

    <section id="strategi" className="strategy-section"><div className="shell strategy-grid"><div className="strategy-heading"><span className="section-label">STRATEGI BELAJAR</span><h2>Jangan hanya membaca.<br/>Bangun recall.</h2><p>Gunakan siklus sederhana agar setiap sesi membantu menemukan bagian yang belum benar-benar dipahami.</p></div><div className="study-loop"><div><span>01</span><strong>Baca satu subbab</strong><p>Pelajari konsep selama 20–25 menit dan cari hubungan antaristilah.</p></div><div><span>02</span><strong>Tutup catatan</strong><p>Jelaskan kembali menggunakan bahasamu sendiri atau gambar alur.</p></div><div><span>03</span><strong>Coba langsung</strong><p>Cek IP address, kelola permission, atau buat tabel database sederhana.</p></div><div><span>04</span><strong>Perbaiki celah</strong><p>Catat bagian yang salah, pelajari ulang, lalu uji lagi setelah jeda.</p></div></div></div></section>

    <section id="evaluasi" className="review shell"><div className="review-heading"><span className="section-label">EVALUASI RINGKAS</span><h2>Tiga pertanyaan untuk<br/>menguji cara berpikir.</h2><p>Kuis dibuat singkat. Fokus utama situs ini tetap materi dan pemahaman konsep.</p></div><div className="question-list">{reviewQuestions.map((q,i)=><article key={q.question}><span>0{i+1}</span><h3>{q.question}</h3><details><summary>Lihat jawaban dan penjelasan</summary><p><strong>{q.answer}</strong> — {q.explanation}</p></details></article>)}</div></section>

    <section id="glosarium" className="glossary-section"><div className="shell"><div className="glossary-heading"><div><span className="section-label">GLOSARIUM INTI</span><h2>Istilah yang perlu<br/>langsung dikenali.</h2></div><p>Gunakan istilah global standard IT saat belajar. Penjelasan berikut membantu memahami fungsi dan konteksnya.</p></div><div className="glossary-grid">{glossary.map(g=><div key={g.term}><strong>{g.term}</strong><p>{g.meaning}</p></div>)}</div></div></section><SiteFooter/>
  </main>
}
